/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Auth System
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface UserSchema {
  id: number;
  username: string;
  email: string;
}

export interface SignupSchema {
  username: string;
  password: string;
  email: string;
}

export interface TokenObtainPairOutputSchema {
  /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @maxLength 150
     */
  username: string;
  refresh: string;
  access: string;
}

export interface TokenObtainPairInputSchema {
  password: string;
  /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @maxLength 150
     */
  username: string;
}

export interface TokenRefreshOutputSchema {
  refresh: string;
  access: string | null;
}

export interface TokenRefreshInputSchema {
  refresh: string;
}

export interface Schema { [key: string]: unknown }

export interface TokenVerifyInputSchema {
  token: string;
}

export const getAuthSystem = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Get Me
 */
const backendApiGetMe = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserSchema>> => {
    return axiosInstance.get(
      `/api/me`,options
    );
  }

/**
 * @summary Signup
 */
const backendApiSignup = (
    signupSchema: SignupSchema, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserSchema>> => {
    return axiosInstance.post(
      `/api/auth/signup`,
      signupSchema,options
    );
  }

/**
 * @summary Obtain Token
 */
const tokenObtainPair = (
    tokenObtainPairInputSchema: TokenObtainPairInputSchema, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TokenObtainPairOutputSchema>> => {
    return axiosInstance.post(
      `/api/token/pair`,
      tokenObtainPairInputSchema,options
    );
  }

/**
 * @summary Refresh Token
 */
const tokenRefresh = (
    tokenRefreshInputSchema: TokenRefreshInputSchema, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TokenRefreshOutputSchema>> => {
    return axiosInstance.post(
      `/api/token/refresh`,
      tokenRefreshInputSchema,options
    );
  }

/**
 * @summary Verify Token
 */
const tokenVerify = (
    tokenVerifyInputSchema: TokenVerifyInputSchema, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Schema>> => {
    return axiosInstance.post(
      `/api/token/verify`,
      tokenVerifyInputSchema,options
    );
  }

return {backendApiGetMe,backendApiSignup,tokenObtainPair,tokenRefresh,tokenVerify}};
export type BackendApiGetMeResult = AxiosResponse<UserSchema>
export type BackendApiSignupResult = AxiosResponse<UserSchema>
export type TokenObtainPairResult = AxiosResponse<TokenObtainPairOutputSchema>
export type TokenRefreshResult = AxiosResponse<TokenRefreshOutputSchema>
export type TokenVerifyResult = AxiosResponse<Schema>
