/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Auth System
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { customInstance } from './apiClient';
;
export const getBackendApiGetMeUrl = () => {
    return `/api/me`;
};
export const backendApiGetMe = async (options) => {
    return customInstance(getBackendApiGetMeUrl(), {
        ...options,
        method: 'GET'
    });
};
export const getBackendApiGetMeQueryKey = () => {
    return [
        `/api/me`
    ];
};
export const getBackendApiGetMeQueryOptions = (options) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getBackendApiGetMeQueryKey();
    const queryFn = ({ signal }) => backendApiGetMe({ signal, ...requestOptions });
    return { queryKey, queryFn, ...queryOptions };
};
/**
 * @summary Get Me
 */
export function useBackendApiGetMe(options) {
    const queryOptions = getBackendApiGetMeQueryOptions(options);
    const query = useQuery(queryOptions);
    return { ...query, queryKey: queryOptions.queryKey };
}
;
export const getBackendApiSignupUrl = () => {
    return `/api/auth/signup`;
};
export const backendApiSignup = async (signupSchema, options) => {
    return customInstance(getBackendApiSignupUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(signupSchema)
    });
};
export const getBackendApiSignupMutationOptions = (options) => {
    const mutationKey = ['backendApiSignup'];
    const { mutation: mutationOptions, request: requestOptions } = options ?
        options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
            options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey, }, request: undefined };
    const mutationFn = (props) => {
        const { data } = props ?? {};
        return backendApiSignup(data, requestOptions);
    };
    return { mutationFn, ...mutationOptions };
};
/**
* @summary Signup
*/
export const useBackendApiSignup = (options) => {
    return useMutation(getBackendApiSignupMutationOptions(options));
};
;
export const getTokenObtainPairUrl = () => {
    return `/api/token/pair`;
};
export const tokenObtainPair = async (tokenObtainPairInputSchema, options) => {
    return customInstance(getTokenObtainPairUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(tokenObtainPairInputSchema)
    });
};
export const getTokenObtainPairMutationOptions = (options) => {
    const mutationKey = ['tokenObtainPair'];
    const { mutation: mutationOptions, request: requestOptions } = options ?
        options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
            options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey, }, request: undefined };
    const mutationFn = (props) => {
        const { data } = props ?? {};
        return tokenObtainPair(data, requestOptions);
    };
    return { mutationFn, ...mutationOptions };
};
/**
* @summary Obtain Token
*/
export const useTokenObtainPair = (options) => {
    return useMutation(getTokenObtainPairMutationOptions(options));
};
;
export const getTokenRefreshUrl = () => {
    return `/api/token/refresh`;
};
export const tokenRefresh = async (tokenRefreshInputSchema, options) => {
    return customInstance(getTokenRefreshUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(tokenRefreshInputSchema)
    });
};
export const getTokenRefreshMutationOptions = (options) => {
    const mutationKey = ['tokenRefresh'];
    const { mutation: mutationOptions, request: requestOptions } = options ?
        options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
            options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey, }, request: undefined };
    const mutationFn = (props) => {
        const { data } = props ?? {};
        return tokenRefresh(data, requestOptions);
    };
    return { mutationFn, ...mutationOptions };
};
/**
* @summary Refresh Token
*/
export const useTokenRefresh = (options) => {
    return useMutation(getTokenRefreshMutationOptions(options));
};
;
export const getTokenVerifyUrl = () => {
    return `/api/token/verify`;
};
export const tokenVerify = async (tokenVerifyInputSchema, options) => {
    return customInstance(getTokenVerifyUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(tokenVerifyInputSchema)
    });
};
export const getTokenVerifyMutationOptions = (options) => {
    const mutationKey = ['tokenVerify'];
    const { mutation: mutationOptions, request: requestOptions } = options ?
        options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
            options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey, }, request: undefined };
    const mutationFn = (props) => {
        const { data } = props ?? {};
        return tokenVerify(data, requestOptions);
    };
    return { mutationFn, ...mutationOptions };
};
/**
* @summary Verify Token
*/
export const useTokenVerify = (options) => {
    return useMutation(getTokenVerifyMutationOptions(options));
};
