/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Auth System
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
export const getAuthSystem = (axiosInstance = axios) => {
    /**
     * @summary Get Me
     */
    const backendApiGetMe = (options) => {
        return axiosInstance.get(`/api/me`, options);
    };
    /**
     * @summary Signup
     */
    const backendApiSignup = (signupSchema, options) => {
        return axiosInstance.post(`/api/auth/signup`, signupSchema, options);
    };
    /**
     * @summary Obtain Token
     */
    const tokenObtainPair = (tokenObtainPairInputSchema, options) => {
        return axiosInstance.post(`/api/token/pair`, tokenObtainPairInputSchema, options);
    };
    /**
     * @summary Refresh Token
     */
    const tokenRefresh = (tokenRefreshInputSchema, options) => {
        return axiosInstance.post(`/api/token/refresh`, tokenRefreshInputSchema, options);
    };
    /**
     * @summary Verify Token
     */
    const tokenVerify = (tokenVerifyInputSchema, options) => {
        return axiosInstance.post(`/api/token/verify`, tokenVerifyInputSchema, options);
    };
    return { backendApiGetMe, backendApiSignup, tokenObtainPair, tokenRefresh, tokenVerify };
};
