/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Auth System
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './apiClient';
export interface UserSchema {
  id: number;
  username: string;
  email: string;
}

export interface SignupSchema {
  username: string;
  password: string;
  email: string;
}

export interface TokenObtainPairOutputSchema {
  /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @maxLength 150
     */
  username: string;
  refresh: string;
  access: string;
}

export interface TokenObtainPairInputSchema {
  password: string;
  /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @maxLength 150
     */
  username: string;
}

export interface TokenRefreshOutputSchema {
  refresh: string;
  access: string | null;
}

export interface TokenRefreshInputSchema {
  refresh: string;
}

export interface Schema { [key: string]: unknown }

export interface TokenVerifyInputSchema {
  token: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Me
 */
export type backendApiGetMeResponse200 = {
  data: UserSchema
  status: 200
}

export type backendApiGetMeResponseSuccess = (backendApiGetMeResponse200) & {
  headers: Headers;
};
;

export type backendApiGetMeResponse = (backendApiGetMeResponseSuccess)

export const getBackendApiGetMeUrl = () => {




  return `/api/me`
}

export const backendApiGetMe = async ( options?: RequestInit): Promise<backendApiGetMeResponse> => {

  return customInstance<backendApiGetMeResponse>(getBackendApiGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBackendApiGetMeQueryKey = () => {
    return [
    `/api/me`
    ] as const;
    }


export const getBackendApiGetMeQueryOptions = <TData = Awaited<ReturnType<typeof backendApiGetMe>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof backendApiGetMe>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBackendApiGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof backendApiGetMe>>> = ({ signal }) => backendApiGetMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof backendApiGetMe>>, TError, TData> & { queryKey: QueryKey }
}

export type BackendApiGetMeQueryResult = NonNullable<Awaited<ReturnType<typeof backendApiGetMe>>>
export type BackendApiGetMeQueryError = unknown


/**
 * @summary Get Me
 */

export function useBackendApiGetMe<TData = Awaited<ReturnType<typeof backendApiGetMe>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof backendApiGetMe>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBackendApiGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Signup
 */
export type backendApiSignupResponse201 = {
  data: UserSchema
  status: 201
}

export type backendApiSignupResponseSuccess = (backendApiSignupResponse201) & {
  headers: Headers;
};
;

export type backendApiSignupResponse = (backendApiSignupResponseSuccess)

export const getBackendApiSignupUrl = () => {




  return `/api/auth/signup`
}

export const backendApiSignup = async (signupSchema: SignupSchema, options?: RequestInit): Promise<backendApiSignupResponse> => {

  return customInstance<backendApiSignupResponse>(getBackendApiSignupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signupSchema,)
  }
);}




export const getBackendApiSignupMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof backendApiSignup>>, TError,{data: SignupSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof backendApiSignup>>, TError,{data: SignupSchema}, TContext> => {

const mutationKey = ['backendApiSignup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof backendApiSignup>>, {data: SignupSchema}> = (props) => {
          const {data} = props ?? {};

          return  backendApiSignup(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BackendApiSignupMutationResult = NonNullable<Awaited<ReturnType<typeof backendApiSignup>>>
    export type BackendApiSignupMutationBody = SignupSchema
    export type BackendApiSignupMutationError = unknown

    /**
 * @summary Signup
 */
export const useBackendApiSignup = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof backendApiSignup>>, TError,{data: SignupSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof backendApiSignup>>,
        TError,
        {data: SignupSchema},
        TContext
      > => {
      return useMutation(getBackendApiSignupMutationOptions(options));
    }

/**
 * @summary Obtain Token
 */
export type tokenObtainPairResponse200 = {
  data: TokenObtainPairOutputSchema
  status: 200
}

export type tokenObtainPairResponseSuccess = (tokenObtainPairResponse200) & {
  headers: Headers;
};
;

export type tokenObtainPairResponse = (tokenObtainPairResponseSuccess)

export const getTokenObtainPairUrl = () => {




  return `/api/token/pair`
}

export const tokenObtainPair = async (tokenObtainPairInputSchema: TokenObtainPairInputSchema, options?: RequestInit): Promise<tokenObtainPairResponse> => {

  return customInstance<tokenObtainPairResponse>(getTokenObtainPairUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tokenObtainPairInputSchema,)
  }
);}




export const getTokenObtainPairMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tokenObtainPair>>, TError,{data: TokenObtainPairInputSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof tokenObtainPair>>, TError,{data: TokenObtainPairInputSchema}, TContext> => {

const mutationKey = ['tokenObtainPair'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tokenObtainPair>>, {data: TokenObtainPairInputSchema}> = (props) => {
          const {data} = props ?? {};

          return  tokenObtainPair(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TokenObtainPairMutationResult = NonNullable<Awaited<ReturnType<typeof tokenObtainPair>>>
    export type TokenObtainPairMutationBody = TokenObtainPairInputSchema
    export type TokenObtainPairMutationError = unknown

    /**
 * @summary Obtain Token
 */
export const useTokenObtainPair = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tokenObtainPair>>, TError,{data: TokenObtainPairInputSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof tokenObtainPair>>,
        TError,
        {data: TokenObtainPairInputSchema},
        TContext
      > => {
      return useMutation(getTokenObtainPairMutationOptions(options));
    }

/**
 * @summary Refresh Token
 */
export type tokenRefreshResponse200 = {
  data: TokenRefreshOutputSchema
  status: 200
}

export type tokenRefreshResponseSuccess = (tokenRefreshResponse200) & {
  headers: Headers;
};
;

export type tokenRefreshResponse = (tokenRefreshResponseSuccess)

export const getTokenRefreshUrl = () => {




  return `/api/token/refresh`
}

export const tokenRefresh = async (tokenRefreshInputSchema: TokenRefreshInputSchema, options?: RequestInit): Promise<tokenRefreshResponse> => {

  return customInstance<tokenRefreshResponse>(getTokenRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tokenRefreshInputSchema,)
  }
);}




export const getTokenRefreshMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tokenRefresh>>, TError,{data: TokenRefreshInputSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof tokenRefresh>>, TError,{data: TokenRefreshInputSchema}, TContext> => {

const mutationKey = ['tokenRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tokenRefresh>>, {data: TokenRefreshInputSchema}> = (props) => {
          const {data} = props ?? {};

          return  tokenRefresh(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TokenRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof tokenRefresh>>>
    export type TokenRefreshMutationBody = TokenRefreshInputSchema
    export type TokenRefreshMutationError = unknown

    /**
 * @summary Refresh Token
 */
export const useTokenRefresh = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tokenRefresh>>, TError,{data: TokenRefreshInputSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof tokenRefresh>>,
        TError,
        {data: TokenRefreshInputSchema},
        TContext
      > => {
      return useMutation(getTokenRefreshMutationOptions(options));
    }

/**
 * @summary Verify Token
 */
export type tokenVerifyResponse200 = {
  data: Schema
  status: 200
}

export type tokenVerifyResponseSuccess = (tokenVerifyResponse200) & {
  headers: Headers;
};
;

export type tokenVerifyResponse = (tokenVerifyResponseSuccess)

export const getTokenVerifyUrl = () => {




  return `/api/token/verify`
}

export const tokenVerify = async (tokenVerifyInputSchema: TokenVerifyInputSchema, options?: RequestInit): Promise<tokenVerifyResponse> => {

  return customInstance<tokenVerifyResponse>(getTokenVerifyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tokenVerifyInputSchema,)
  }
);}




export const getTokenVerifyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tokenVerify>>, TError,{data: TokenVerifyInputSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof tokenVerify>>, TError,{data: TokenVerifyInputSchema}, TContext> => {

const mutationKey = ['tokenVerify'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tokenVerify>>, {data: TokenVerifyInputSchema}> = (props) => {
          const {data} = props ?? {};

          return  tokenVerify(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TokenVerifyMutationResult = NonNullable<Awaited<ReturnType<typeof tokenVerify>>>
    export type TokenVerifyMutationBody = TokenVerifyInputSchema
    export type TokenVerifyMutationError = unknown

    /**
 * @summary Verify Token
 */
export const useTokenVerify = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tokenVerify>>, TError,{data: TokenVerifyInputSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof tokenVerify>>,
        TError,
        {data: TokenVerifyInputSchema},
        TContext
      > => {
      return useMutation(getTokenVerifyMutationOptions(options));
    }
